version: "3.8"
services:
  php:
    build: './php'
    image: php:pwcho
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - ./app/:/var/www/html/
    container_name: 'php'
  httpd:
    build: './httpd'
    image: httpd:pwcho
    depends_on: 
      - php
      - mysql
    ports:
      - "6666:6666"
    networks:
      - backend
      - frontend
    volumes:
      - ./app/:/usr/local/apache2/htdocs/
    container_name: 'web'
  mysql:
    image: mysql:pwcho
    build:
      context: ./mysql
      dockerfile: Dockerfile.debian
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
    container_name: 'db'
networks:
  backend:
  frontend:
